#!/bin/bash

if [ "x${1}" = "x" ]
then
  echo 'Please input file name which you would like remove recursively'
  exit 255
fi

if [ "x${2}" = "x-f" ]
then
  echo 'Remove files:'
  find . -name "${1}"
  find . -name "${1}" | xargs -I "@@" rm -f @@
  exit 0
fi

echo 'We will remove below files if you put "-f" to command':
find . -name "${1}"
exit 0
