#!/bin/bash
################################################################################
# Search a phrase in files of current directory and descendant directories.
#
# Usage:
#&  `echo_yellow "${EXEC_NAME} [--help]" -en`
#     Show this help.
#
#&  `echo_yellow "${EXEC_NAME} <query>" -en`
#&    Search `echo_yellow "<name>" -en` in files of current directory and descendant directories.
################################################################################
BASE_DIR=`cd $(dirname "$0"); pwd`
EXEC_NAME=`basename "$0"`

# Include common functions of bash
for lc_script in `find $BASE_DIR/include -maxdepth 2 -type f -name '*.sh'`
do
. $lc_script
done

# Main process
if [ "x${1}" = "x" ]
then
  echo_red 'Please input query string.'
  echo '--------'
fi

# Show help
if [ "x${1}" = "x" ] || [ "x${1}" = "x--help" ]
then
  inc_helpComponent
  cpnt_help "${BASH_SOURCE[0]}"
  exit
fi

find . -type f -exec grep "${1}" {} \+
