#!/bin/bash
##############################################################################
# Starting section for every command
##############################################################################

################ Init ################
BASE_DIR=`pwd`
DESPATCH_SCRIPT=$0
BIN_DIR=`cd $(dirname "$0"); pwd`

cd ${BIN_DIR}
if [ -f "${BASE_DIR}/config/constant.sh" ] ; then
  . "${BASE_DIR}/config/constant.sh"
fi

# Constants
PRI_IFS=$IFS
CLIENT_DIR=client_repository
TTV_SRC=ttv_source
OUTPUT_DIR=output
SYNC_TRACKER_DIR="${BASE_DIR}/config/.sync_tracker"
EMAIL_LIST_FILE="${BASE_DIR}/config/email_list"

CONNECT_GUESS_SSH=`echo ssh -p ${VAGRANT_SSH_PORT} -i vagrant/.vagrant/machines/default/virtualbox/private_key vagrant@127.0.0.1`
USE_DEFAULT_FUNCTION='. `dirname ${BASH_SOURCE}`/../`basename ${BASH_SOURCE}`'

# Initializing function
for lc_file in `find inc -type f -name '*.sh'`
do
  . $lc_file
done
unset lc_file

# Component functions
for lc_file in `find comp/pjr -type f -name '*.sh'`
do
  . $lc_file
done
unset lc_file

# Parse to get command
DESPATCH_SCRIPT=`cmn_mainBasename "${DESPATCH_SCRIPT}"`
if [ "x" = "x${1}" ]
then
  echo_red "Please use '${DESPATCH_SCRIPT} <command>'"
  comp_help_wrong_despatch
fi

if [ "x${1}" = "x-" ]; then
  SCRIPTNAME=runout
else
  SCRIPTNAME=${1}
fi

CODE_SCRIPT=`find ${BIN_DIR}/cmd -type f -name [[:digit:]][[:digit:]][[:digit:]]_${SCRIPTNAME}`
if [ "x" = "x${CODE_SCRIPT}" ]
then
  echo_red "Not support command '${SCRIPTNAME}'"
  comp_help_wrong_despatch
fi

lc_dir="${BIN_DIR}/fn/${SCRIPTNAME}"
if [ -d "${lc_dir}" ]
then
  if [ -d "${lc_dir}/${TOOL_VCS}" ]; then
    lc_dir="${lc_dir}/${TOOL_VCS}"
  fi

  for lc_file in `find "${lc_dir}" -maxdepth 1 -type f -name '*.sh'`
  do
    . "${lc_file}"
  done
  unset lc_file
fi

################# Parse parameters #################
shift
SCRIPT_CODE=`cmn_mainBasename ${CODE_SCRIPT}`
SCRIPT_CODE=`printf '%d\n' ${SCRIPT_CODE:0:3}`

cd "${BASE_DIR}"
if [ ${SCRIPT_CODE} -lt 500 ]; then
  comp_check_config
fi

################# Run #################
CMN_COUNT=0
. ${CODE_SCRIPT}
cmn_exitNormal
