#!/bin/bash
##############################################################################
# Starting section for every command
##############################################################################

################ Init ################
BIN_DIR=`cd $(dirname "$0"); pwd`
cd ${BIN_DIR}

# Initializing function
for lc_file in `find _inc/ -type f -name '*.sh'`
do
  . $lc_file
done
unset lc_file

if [ "x" = "x${1}" ]
then
  echo_red "Please input your command"
  exit 1;
fi

SCRIPTNAME=${1}
if [ -d "${BIN_DIR}/fnsh/${SCRIPTNAME}" ]
then
  for lc_file in `find "${BIN_DIR}/fnsh/${SCRIPTNAME}" -type f -name '*.sh'`
  do
    . "${lc_file}"
  done
  unset lc_file
fi

################# Parse parameters #################
shift

################# Run #################
BIN_FOLDER=`cmn_mainBasename "${BIN_DIR}"`
BASE_DIR=`cd $(dirname "${BIN_DIR}"); pwd`
cd "${BASE_DIR}"

CMN_COUNT=0
if [ -f ${BIN_FOLDER}/cmdsh/${SCRIPTNAME} ]
then
  . ${BIN_FOLDER}/cmdsh/${SCRIPTNAME}
  cmn_exitNormal
fi

if [ "x" = "x${1}" ]
then
  echo_red "Please input your subroutine of ${SCRIPTNAME}"
  exit 1;
fi

FUNCTION_NAME=${SCRIPTNAME}_${1}
shift
cmn_functionExists ${FUNCTION_NAME}
if [ $? -ne 0 ]
then
  echo_red "Function ${FUNCTION_NAME} doesn't exist"
  exit 1;
fi
${FUNCTION_NAME} $@
cmn_exitNormal