#!/usr/bin/env bash
################################################################################
TEXT_SEARCH=CRLF
if [ "x$1" != "x" ]
then
  TEXT_SEARCH=`echo "${1}" | sed 's#'"'"'#'"'"'"'"'"'"'"'"'#g'`
fi

IGNORE_LIST=' '
if [ -f .findignore ]
then
  while IFS=$'\n' read -r line
  do
    line=`echo "${line}" | sed 's:/*$::'`
    if [ "x${line}" != "x" ]
  then
    IGNORE_LIST="${IGNORE_LIST} ! -path '${line}' "
  fi
  done < .findignore
  IFS=$PRI_IFS
fi

COMMAND="find . -type f ! -path '*/.git/*' ! -path '*/node_modules/*' ${IGNORE_LIST} -exec file '{}' ';' | grep '${TEXT_SEARCH}'"
eval $COMMAND
