#!/bin/bash
################################################################################
# Docker-compose utility command
#
# If the first argument is configured project, it will be working project.
# In the other hand, the project directory will be checked back sequently to
# find out working project.
#
# Usage:
#&  `echo_yellow "${EXEC_NAME} [-h|--help]" -en`
#     Show this help.
#
#&  `echo_yellow "${EXEC_NAME} [<CONFIGURED_WORK_DIR>] <docker-compose arguments>" -en`
################################################################################
BASE_DIR=`cd $(dirname "$0"); pwd`
. $BASE_DIR/../../.env

# Include common functions of bash
for lc_script in `find $BASE_DIR/../../include -maxdepth 2 -type f -name '*.sh'`
do
. $lc_script
done

# Show help
if [ "x${1}" = "x" ] || [ "x${1}" = "x-h" ] || [ "x${1}" = "x--help" ]
then
  inc_itselfHelp
fi

# Go to working directory
function gotoWorkDir() {
  if [ -f $WORK_DIR/provision/docker-compose.yml ]
  then
    WORK_DIR=${WORK_DIR}/provision
    cd ${WORK_DIR}

    return
  fi

  cmn_numMatch '/' "$WORK_DIR"
  if [ $? -le 2 ]
  then
     cmn_exitAbnormal "Could not find provision directory!"
  fi

  cd ..
  WORK_DIR=`pwd`
  gotoWorkDir
}

if [ "x${PROJECT_INDEXES[$1]}" != "x" ]
then
  cmn_isStartWith / ${PROJECT_INDEXES[$1]}
  if [ $? -eq 0 ]
  then
    WORK_DIR=${PROJECT_INDEXES[$1]}/provision
  else
    WORK_DIR=$WORKSPACE/${PROJECT_INDEXES[$1]}/provision
  fi

  if [ ! -f $WORK_DIR/docker-compose.yml ]
  then
    cmn_exitAbnormal "${1} is not configured working project!"
  fi

  cd ${WORK_DIR}
  shift
else
  FOUND_PROJECT=1
  cmn_isStartWith pj $1
  if [ $? -eq 0 ] && [ "x${PROJECT_LIST}" != "x" ] && [ ${#1} -lt 4 ]
  then
    if [ ${#1} -eq 2 ]
    then
      WORK_DIR=$WORKSPACE/${PROJECT_LIST}
    else
      PROJECT_NUMBER=${1:2}
      cmn_isPositiveNumber $PROJECT_NUMBER
      if [ $? -eq 0 ] && [ "x${PROJECT_LIST[$PROJECT_NUMBER]}" != "x" ]
      then
        WORK_DIR=$WORKSPACE/${PROJECT_LIST[$PROJECT_NUMBER]}
      fi
    fi

    if [ -f $WORK_DIR/provision/docker-compose.yml ]
    then
      FOUND_PROJECT=0
      WORK_DIR=$WORK_DIR/provision
    fi
  fi

  if [ $FOUND_PROJECT -eq 0 ]
  then
    cd ${WORK_DIR}
    shift
  else
    WORK_DIR=`pwd`
    if [ "x`dirname $WORK_DIR`" != "xprovision" ]
    then
      gotoWorkDir
    fi
  fi
fi

docker-compose "$@"
