#!/usr/bin/env bash
################################################################################
# Delete files/folders has specified name recursively.
#
# Usage:
#&  `echo_yellow "${EXEC_NAME} [-h|--help]" -en`
#     Show this help.
#
#&  `echo_yellow "${EXEC_NAME} <name>" -en`
#&    Show list files or folders named `echo_yellow "<name>" -en`.
#
#&  `echo_yellow "${EXEC_NAME} <name> -f" -en`
#&    Delete files or folders named `echo_yellow "<name>" -en` recursively.
################################################################################
BASE_DIR=`cd $(dirname "$0"); pwd`
. $BASE_DIR/../../include/src

# Check parameter
if [ "x${1}" = "x" ]
then
  inc_itselfHelp 'Please input file name which you would like to remove recursively.'
fi

# Show help
if [ "x${1}" = "x-h" ] || [ "x${1}" = "x--help" ]
then
  inc_itselfHelp
fi

if [ "x${2}" = "x-f" ]
then
  echo 'Remove files:'
  find . -name "${1}"
  find . -name "${1}" | xargs -I "@@" rm -rf @@
  exit
fi

echo 'We will remove below files if you put "-f" to command':
find . -name "${1}"
exit 0
