#!/usr/bin/env bash
################################################################################
# Search a phrase in files of current directory and descendant directories.
#
# Usage:
#&  `echo_yellow "${EXEC_NAME} [--help]" -en`
#     Show this help.
#
#&  `echo_yellow "${EXEC_NAME} <query>" -en {The first parameter of grep command like -iw}`
#&    Search `echo_yellow "<name>" -en` in files of current directory and descendant directories.
################################################################################
BASE_DIR=`cd $(dirname "$0"); pwd`
. $BASE_DIR/../../include/src

# Check parameter
if [ "x${1}" = "x" ]
then
  inc_itselfHelp 'Please input query string.'
fi

# Show help
if [ "x${1}" = "x" ] || [ "x${1}" = "x--help" ]
then
  inc_itselfHelp
fi

##
# Main process
find . -type f -exec grep $2 "${1}" {} \+
