#!/usr/bin/env bash
################################################################################
OPTIONS=
if [ "x${1:0:1}" = 'x-' ]
then
  OPTIONS="${1}"
  shift
fi

if [ "x$1" = "x" ]
then
  echo please input your search text.
  exit
fi

TEXT_SEARCH=`echo "${1}" | sed 's#'"'"'#'"'"'"'"'"'"'"'"'#g'`
shift

IGNORE_LIST=' '
if [ -f .findignore ]
then
  while IFS=$'\n' read -r line
  do
    line=`echo "${line}" | sed 's:/*$::'`
    if [ "x${line}" != "x" ]
    then
      if [ -e "${line}" ]
      then
        IGNORE_LIST="${IGNORE_LIST} ! -name '${line}'"
      else
        IGNORE_LIST="${IGNORE_LIST} ! -path '${line}' "
      fi
    fi
  done < .findignore
  IFS=$PRI_IFS
fi

COMMAND="find . -type f ! -path '*/.git/*' ! -path '*/node_modules/*' ${IGNORE_LIST} -exec grep ${OPTIONS} '${TEXT_SEARCH}' {} \+"

OPTIONS=
for SECONDARY_TS in $@
do
  if [ "x${SECONDARY_TS:0:1}" = 'x-' ]
  then
    OPTIONS="${OPTIONS} ${SECONDARY_TS}"
  else
    COMMAND="${COMMAND} | grep ${OPTIONS} '${SECONDARY_TS}'"
    OPTIONS=
  fi
done

eval $COMMAND 2>/dev/null

