VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "{VAGRANT_BOX_NAME}"
  config.vm.box_url = "{VAGRANT_BOX_URL}"

  config.vm.network "private_network", ip: "{VAGRANT_GUESS_IP}"
  config.vm.network :forwarded_port, guest: 22, host: {VAGRANT_SSH_PORT}, id: "ssh"

  config.vm.synced_folder "../{TTV_SRC}", "/data/{PROJECT_ID}", create: true, owner: 'vagrant', group: 'vagrant', mount_options: ['dmode=777,fmode=776']

  config.vm.provider :virtualbox do |vb|
    vb.name = "{PROJECT_ID}"
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "off"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "off"]
  end
{VAGRANT_PROVISION}
end
