#!/usr/bin/env bash
################################################################################
# Open DiffMerge application (Backup command).
#&Need to set up the path to diffmerge application `echo_yellow "DIFFMERGE_APP=" -en`
#
# Usage:
#&  `echo_yellow "${EXEC_NAME}" -en`
#     Open and available 2 files: CP_0.html and CP_1.html.
#
#&  `echo_yellow "${EXEC_NAME} -" -en`
#     Open application only (not available file).
#
#&  `echo_yellow "${EXEC_NAME} --" -en`
#     Open and available 2 files: CP_2.html and CP_3.html.
#
#&  `echo_yellow "${EXEC_NAME} ---" -en`
#     Open and available 3 files: CP_0.html and CP_1.html and CP_2.html.
#
#&  `echo_yellow "${EXEC_NAME} <n> <file>" -en`
#&  `echo_green "<n>" -en`: file numeric
#&    Add <file> content to CP_`echo_green "<n>" -en`.html.
#
#&  `echo_yellow "${EXEC_NAME} help|-h|--help" -en`
#     Show this help.
################################################################################
DIFF_DIR=~/comparision_files
if [ ! -d $DIFF_DIR ]
then
  mkdir ~/comparision_files
  lc_strlist='0 1 2 3'
  for lc in $lc_strlist
  do
    if [ ! -f "${DIFF_DIR}/CP_${lc}.html" ]
    then
      touch "${DIFF_DIR}/CP_${lc}.html"
    fi
  done
fi

BASE_DIR=`cd $(dirname "$0"); pwd`
. $BASE_DIR/../../include/src

if [ "x${1}" = "x-h" ] || [ "x${1}" = "x--help" ] || [ "x${1}" = "xhelp" ]
then
  inc_itselfHelp
elif [ "x${1}" = "x" ]
then
  open $DIFFMERGE_APP --args $DIFF_DIR/CP_0.html $DIFF_DIR/CP_1.html
elif [ "x${1}" = "x-" ]
then
  shift
  if [ "x${1}" = "x" ]
  then
    open $DIFFMERGE_APP
  else
    open $DIFFMERGE_APP --args "$@"
  fi
elif [ "x${1}" = "x--" ]
then
  open $DIFFMERGE_APP --args $DIFF_DIR/CP_2.html $DIFF_DIR/CP_3.html
elif [ "x${1}" = "x---" ]
then
  open $DIFFMERGE_APP --args $DIFF_DIR/CP_0.html $DIFF_DIR/CP_1.html $DIFF_DIR/CP_2.html
else
  if [ "x${2}" != "x" ] && [ -f "$2" ]
  then
    cat "$2" > $DIFF_DIR/CP_${1}.html
  else
    inc_itselfHelp 'Please input the second parameter is a readable file!'
  fi
fi
