#!/bin/bash
PRI_IFS=$IFS
INDENT_SPACES='  '

if [ "x$0" != 'x-bash' ]
then
  EXEC_NAME=`basename "$0"`
else
  EXEC_NAME=
fi

SHELL_NAME=`basename $SHELL`

# COMMAND_DIR is declared in profile when start bash
if [ "x${COMMAND_DIR}" = "x" ]
then
  # Bash or zsh
  COMMAND_DIR=`cd "$(dirname "${BASH_SOURCE[0]:-${(%):-%x}}")"/.. >/dev/null && pwd`

  # Should not use below variable in common functions (cmn_)
  WORK_DIR=`pwd`
fi

# Include all sh files of this folder and its sub folders
for lc_script in `find $COMMAND_DIR/include -maxdepth 2 -type f -name '*.sh'`
do
  . $lc_script
done
unset lc_script
