#!/bin/bash
################################################################################
# Open DiffMerge application.
#
# Usage:
#&  `echo_yellow "${EXEC_NAME}" -en`
#     Open and available 2 files: CP_0.html and CP_1.html.
#
#&  `echo_yellow "${EXEC_NAME} -" -en`
#     Open application only (not available file).
#
#&  `echo_yellow "${EXEC_NAME} --" -en`
#     Open and available 2 files: CP_2.html and CP_3.html.
#
#&  `echo_yellow "${EXEC_NAME} --" -en`
#     Open and available 3 files: CP_0.html and CP_1.html and CP_2.html.
#
#&  `echo_yellow "${EXEC_NAME} <n> <file>" -en`
#&  `echo_green "<n>" -en`: file numeric
#&    Add <file> content to CP_`echo_green "<n>" -en`.html.
#
#&  `echo_yellow "${EXEC_NAME} help|-h|--help" -en`
#     Show this help.
################################################################################
APP_EXE="/c/Program Files/SourceGear/Common/DiffMerge/sgdm.exe"
DIFF_DIR=~/OneDrive/track/compare

BASE_DIR=`cd $(dirname "$0"); pwd`

##
# Include common functions of bash
for lc_script in `find $BASE_DIR/../../include -maxdepth 2 -type f -name '*.sh'`
do
. $lc_script
done

if [ "x${1}" = "x-h" ] || [ "x${1}" = "x--help" ] || [ "x${1}" = "xhelp" ]
then
  inc_itselfHelp
elif [ "x${1}" = "x" ]
then
  "$APP_EXE" $DIFF_DIR/CP_0.html $DIFF_DIR/CP_1.html
elif [ "x${1}" = "x-" ]
then
  shift
  "$APP_EXE" "$@"
elif [ "x${1}" = "x--" ]
then
  "$APP_EXE" $DIFF_DIR/CP_2.html $DIFF_DIR/CP_3.html
elif [ "x${1}" = "x---" ]
then
  "$APP_EXE" $DIFF_DIR/CP_0.html $DIFF_DIR/CP_1.html $DIFF_DIR/CP_2.html
else
  if [ "x${2}" != "x" ] && [ -f "$2" ]
  then
    cat "$2" > $DIFF_DIR/CP_${1}.html
  else
    inc_itselfHelp 'Please input the second parameter is a readable file!'
  fi
fi
